[package]
name = "kea_gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { version = "0.37.0", features = ["linked"] }
ash-window = "0.12.0"
raw-window-handle="0.5.0"
winit = "0.27.4"
log = "0.4.17"
gpu-allocator = "0.19.1"
glam = "0.21.3"
memoffset = "0.6.5"
num-traits = "0.2.15"
downcast-rs = "1.2.0"

spirv-builder = { git = "https://github.com/EmbarkStudios/rust-gpu" }
kea_gpu_shaderlib = { path = "../kea_gpu_shaderlib" }
