[workspace]
members = [
    "kea_gpu",
    "kea_gpu_shaderlib",
    "kea_renderer",
    "kea_renderer_shaders",
]

# https://github.com/EmbarkStudios/rust-gpu/issues/938
[patch.crates-io]
libm = { git = "https://github.com/rust-lang/libm", tag = "0.2.5" }