[package]
name = "kea_gpu_shaderlib"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
spirv-std = { version = "0.4.0-alpha.17", features = ["glam"] }