[package]
name = "kea_renderer_shaders"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
kea_gpu_shaderlib = { path = "../kea_gpu_shaderlib" }
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu", features = [
    "glam",
] }
